name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-automerge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable automerge
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
