name: Environment Prod - Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Terraform Plan - Prod
    runs-on: ubuntu-latest
    environment: prod-ro
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/environment/prod
          label: prod
          backend_config: >
            bucket=${{ vars.STATE_BUCKET }},
            key=dnd-planner/prod/terraform.tfstate,
            region=${{ vars.AWS_REGION }}
