name: Environment Test - Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform Apply - Test
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TEST_IAC_RW_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Init
        working-directory: terraform/environment/test
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.STATE_BUCKET }}" \
            -backend-config="key=dnd-planner/test/terraform.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.LOCK_TABLE }}"

      - name: Terraform Plan
        working-directory: terraform/environment/test
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/environment/test
        run: terraform apply -auto-approve tfplan

      - name: Deploy Prod
        uses: nick-fields/retry-action@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            gh workflow run environment-prod-deploy.yaml -r main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
